---
name: build

'on':
  push:
    branches:
      - master
      - add-github-actions
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        go: [1.13, 1.14]
      fail-fast: false

    env:
      GOPROXY: https://proxy.golang.org
      GOPATH: ${{ github.workspace }}/go

    runs-on: ${{ matrix.os }}

    steps:

      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: display env
        run: |
          env

      - name: display go env
        run: |
          go env

      - name: build and test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make nodeup examples test
          make github-actions
