---
name: build

'on':
  push:
    branches:
      - master
      - add-github-actions
  pull_request:
    branches: ["*"]

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: /home/runner/work/kops/go

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        go: [1.13, 1.14]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ go.module-path }}

      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: build and test
        working-directory: ${{ go.module-path }}
        run: |
          env
          make nodeup examples test
          make github-actions
